---
title: "Curriculum Vitae"
pagetitle: "Alexandre R. Bevington"
output:
  html_document:
    toc: true
    number_sections: true
    toc_float: 
      collapsed: false
      smooth_scroll: true
---

<link rel="stylesheet" href="../styles.css" type="text/css">
<link rel="stylesheet" href="../academicicons/css/academicons.min.css"/>

Last updated `r lubridate::today()`

# Employment

-   **Research Hydrologist**, 2019-Present\
    Ministry of Forests, Lands, Natural Resource Operations and Rural Development\
    Prince George, British Columbia

-   **Research Earth Scientist**, 2015-2019\
    Ministry of Forests, Lands, Natural Resource Operations and Rural Development\
    Prince George, British Columbia

<!-- -   **College Instructor**, 2013-2014\ -->
<!--     Yukon College\ -->
<!--     Whitehorse, Yukon -->

<!-- -   **Graduate Field Researcher in Permafrost Science**, 2010-2014\ -->
<!--     University of Ottawa / Geological Survey of Canada\ -->
<!--     Ottawa, Ontario and Whitehorse, Yukon -->

<!-- -   **Teaching Assistant**, 2012-2013\ -->
<!--     University of Ottawa\ -->
<!--     Ottawa, Ontario -->

<!-- -   **Editorial Assistant**, 2012-2012\ -->
<!--     Canadian International Polar Year, Aboriginal Affairs and Northern Development Canada\ -->
<!--     Ottawa, Ontario -->

# Education

-   **PhD in Natural Resources and Environmental Studies**, Ongoing\
    University of Northern British Columbia (Prince George, British Columbia)\
    "Accelerated change in the mountain cryosphere of British Columbia"\
    Supervisors: Dr. B. Menounos and Dr. M Geertsema

-   **MSc in Physical Geography**, 2015\
    University of Ottawa (Ottawa, Ontario)\
    "Towards a TTOP-model of permafrost distribution for Yukon and British Columbia"\
    Supervisor: Dr. A. Lewkowicz

<!-- -   **BSc with Honors in Physical Geography**, 2011\ -->
<!--     University of Ottawa (Ottawa, Canada)\ -->
<!--     "Characteristics of the last five surges of Lowell Glacier, Yukon, Canada, since 1948"\ -->
<!--     Supervisor: Dr. L. Copland -->
