---
title: "Publications"
pagetitle: "GeoWS - Publications"
output:
  html_document:
    toc: true
    number_sections: true
    toc_float: 
      collapsed: false
      smooth_scroll: true
---

<link rel="stylesheet" href="../styles.css" type="text/css">


<link rel="stylesheet" href="../academicicons/css/academicons.min.css"/>

Last updated `r lubridate::today()`

# Peer-reviewed publications

1.  **Bevington, AR** and B Menounos. 2025. [Glaciers in western North America and Alaska experience exceptional rise of transient snowlines over the satellite era](https://iopscience.iop.org/article/10.1088/1748-9326/adc9ca). *Environmental Research Letters.*

2.  Mumma, M, **AR Bevington**, S Marshall and M Gillingham. 2024. [Delineating wildfire burns and regrowth using satellite imagery to assess moose (Alces) spatial responses to burns](https://doi.org/10.1002/ecs2.4793). *Ecosphere.*

3.  Herring, T, AG Lewkowicz, ..., **AR Bevington**, .... 2024. [The Canadian Permafrost Electrical Resistivity Survey Database (CPERS): 15 years of permafrost resistivity data](https://doi.org/10.1139/as-2023-0058). *Arctic Science.*

4.  Griesbauer, H and **AR Bevington**. 2024. [Recent changes in forest structure and growth at the alpine-treeline ecotone in the Rocky and Columbia Mountains of central British Columbia, Canada](https://doi.org/10.1111/jbi.14778). *Journal of Biogeography.*

5.  **Bevington, AR** and B Menounos. 2022. [Accelerated change in the glaciated environments of western Canada revealed through trend analysis of optical satellite imagery](https://doi.org/10.1016/j.rse.2021.112862). *Remote Sensing of Environment.*

6.  Mumma, MA, MP Gillingham, S Marshall, C Procter, **AR Bevington** and M Scheideman. 2021. [Regional moose (Alces) responses to forestry cutblocks are driven by landscape-scale patterns of vegetation composition and regrowth](https://doi.org/10.1016/j.foreco.2020.118763). *Forest Ecology and Management.*

7.  Geertsema, M. and **AR Bevington**. 2020. [A cautionary note for rock avalanche field investigation-recent sequential and overlapping landslides in British Columbia](https://doi.org/10.1139/cgj-2019-0751). *Canadian Geotechnical Journal.*

8.  Gleason, HG, **AR Bevington** and VN Foord. 2020. [Classification of clustered snow off dates over British Columbia, Canada, from mean sea level pressure](https://doi.org/10.1080/07055900.2020.1845116). *Atmosphere-Ocean, 58, 333--350.*

9.  Mumma, MA, MP Gillingham, S Marshall, C Procter, **AR Bevington** and M Scheideman. 2020. [Regional moose (Alces alces) responses to forestry cutblocks are driven by landscape-scale patterns of vegetation composition and regrowth](https://doi.org/10.1016/j.foreco.2020.118763). *Forest Ecology and Management, 481, 1--11.*

10. Ban, Y, P Zhang, A Nascetti, **AR Bevington** and MA Wulder. 2020. [Near real-time wildfire progression monitoring with Sentinel-1 SAR time series and deep learning](https://doi.org/10.1038/s41598-019-56967-x). *Scientific Reports, 10, 1322.*

11. Barth, S, M Geertsema, **AR Bevington**, AL Bird, JJ Clague, T Millard, PT Bobrowsky, A Hasler and H Liu. 2020. [Landslide response to the 27 October 2012 earthquake (MW 7.8), southern Haida Gwaii, British Columbia, Canada](https://doi.org/10.1007/s10346-019-01292-7). *Landslides, 17, 517--526.*

12. Deijns, AAJ, **AR Bevington**, F van Zadelhoff, SM de Jong, M Geertsema and S McDougall. 2020. [Semi-automated detection of landslide timing using harmonic modelling of satellite imagery, Buckinghorse River, Canada](https://doi.org/10.1016/j.jag.2019.101943). *International Journal of Applied Earth Observation and Geoinformation, 84, 101943.*

13. Shugar, DH, A Burr, UK Haritashya, JS Kargel, CS Watson, MC Kennedy, **AR Bevington**, RA Betts, S Harrison and K Strattman. 2020. [Rapid worldwide growth of glacial lakes since 1990](https://doi.org/10.1038/s41558-020-0855-4). *Nature Climate Change, 10, 939--945.*

1.  **Bevington AR**, HE Gleason and VN Foord. 2020. [Snow cover timing from satellite imagery: Opportunities for near-real-time mapping and seasonal forecasting](http://a100.gov.bc.ca/pub/eirs/viewDocumentDetail.do?fromStatic=true&repository=BDP&documentId=13100). *BC Technical Report 129. Government of British Columbia. Victoria, BC.Book Chapters*

14. Geertsema M and **AR Bevington**. 2019. [A cautionary note for rock avalanche field investigation -- recent sequential and overlapping landslides in British Columbia](https://doi.org/10.1139/cgj-2019-0751). *Canadian Geotechnical Journal.*

15. **Bevington AR**, H Gleason, V Foord, H Griesbauer and WC Floyd. 2019. [Regional influence of ocean--atmosphere teleconnections on the timing and duration of MODIS-derived snow cover in British Columbia, Canada](https://doi.org/10.5194/tc-13-2693-2019). *The Cryosphere, 13, 2693--2712.*

16. Brideau MA, DH Shugar, **AR Bevington**, M Willis and C Wong. 2019. [Evolution of the 2014 Vulcan Creek landslide-dammed lake, Yukon, Canada, using field and remote survey techniques](https://doi.org/10.1007/s10346-019-01199-3). *Landslides, 16, 1823--1840.*

17. **Bevington AR**, H Gleason, X Giroux-Bougard and J de Jong. 2018. [A review of free optical satellite imagery for watershed scale landscape analysis](https://doi.org/10.22230/jwsm.2018v2n2a18). *Confluence: Journal of Watershed Science, 2, 1--22.*

18. Tanski G, H Bergstedt, **AR Bevington**, et al. 2019. [The Permafrost Young Researchers Network (PYRN) is getting older: The past, present, and future of our evolving community](https://doi.org/10.1017/S0032247418000645). *Polar Record. 1-4.*

19. Leverkus S, SD Fuhlendorf, M Geertsema, BD Allred, M Gregory, **AR Bevington**, DM Engle and JD Scasta. 2018. [Resource selection of free-ranging horses influenced by fire in northern Canada](https://doi.org/10.26077/j5px-af63). *Human--Wildlife Interactions 12, 85--101.*

20. Kargel JS, GJ Leonard ,DH Shugar, UK Haritashya, **AR Bevington**, et al. 2015. [Geomorphic and tectonic controls of geohazards induced by Nepal's 2015Gorkha earthquake](https://doi.org/10.1126/science.aac8353). *Science, 351, 6269.*

21. Magnin F, M Krautblatter, P Deline, L Ravanel, E Malet and **AR Bevington**. 2015. [Determination of warm, sensitive permafrost areas in near‐vertical rockwalls and evaluation of distributed models by electrical resistivity tomography](https://doi.org/10.1002/2014JF003351). Journal of Geophysical Research Earth Surface, 120, 745--762.

22. **Bevington AR** and L Copland. 2014. [Characteristics of the last five surges of Lowell Glacier, Yukon, Canada, since 1948](https://doi.org/10.3189/2014JoG13J134). *Journal of Glaciology, 60, 219*

# Book chapters

1.  Menounos B, **AR Bevington** and Geertsema, M. 2017. [Glacier Environments](https://doi.org/10.1007/978-3-319-12127-7_143-1). *In: Encyclopedia of Engineering Geology. P.T. Bobrowsky and B. Marker (eds.).*
2.  **Bevington AR**, JJ Clague, T Millard, IJ Walker and M Geertsema. 2017. [The Diverse Landscapes of Haida Gwaii](https://doi.org/10.1007/978-3-319-44595-3_21). *In: Landscapes and Landforms of Western Canada. O. Slaymaker (ed.).*
3.  **Bevington AR**, MA Brideau and M Geertsema. 2016. [Mountain Environments](https://doi.org/10.1007/978-3-319-12127-7_209-1). *In: Encyclopedia of Engineering Geology. P.T. Bobrowsky and B. Marker (eds.).*

# Refereed conference papers

1.  Brideau MA, **AR Bevington**, AG Lewkowicz and D Stead. 2015. [Engineering geology,electrical resistivity tomography and displacement monitoring of the DawsonCity Landslide, Yukon](https://www.researchgate.net/publication/281939062_Engineering_Geology_Electrical_Resistivity_Tomography_and_Displacement_Monitoring_of_the_Dawson_City_Landslide_Yukon). *Proceedings of GEOQuebec 2015 Geotechnical Conference and 7th Canadian Permafrost Conference, Quebec City, Canada.*
2.  Smith SL, AG Lewkowicz, M Ednie, M Duguay and **AR Bevington**. 2015. [Characterization ofpermafrost thermal state in the southern Yukon](https://www.researchgate.net/publication/312623215_Characterization_of_Permafrost_Thermal_State_in_the_Southern_Yukon). *Proceedings of GEOQuebec 2015 Geotechnical Conference and 7th Canadian Permafrost Conference, Quebec City, Canada.*
3.  **Bevington AR** and AG Lewkowicz. 2015. [Assessment of a landcover driven TTOP-model for mountain and lowland permafrost using field data, southern Yukon and northern British Columbia, Canada](https://www.researchgate.net/publication/282649555_Assessment_of_a_land_cover_driven_TTOP_model_for_mountain_and_lowland_permafrost_using_field_data_southern_Yukon_and_northern_British_Columbia_Canada). *Proceedings of GEOQuebec 2015 Geotechnical Conference and 7th Canadian Permafrost Conference, Quebec City, Canada.*

# Presentations
1.  Brideau MA, **AR Bevington**, AG Lewkowicz and D Stead. 2015. [Engineering geology,electrical resistivity tomography and displacement monitoring of the DawsonCity Landslide, Yukon](https://www.researchgate.net/publication/281939062_Engineering_Geology_Electrical_Resistivity_Tomography_and_Displacement_Monitoring_of_the_Dawson_City_Landslide_Yukon). *Proceedings of GEOQuebec 2015 Geotechnical Conference and 7th Canadian Permafrost Conference, Quebec City, Canada.*
2.  Smith SL, AG Lewkowicz, M Ednie, M Duguay and **AR Bevington**. 2015. [Characterization ofpermafrost thermal state in the southern Yukon](https://www.researchgate.net/publication/312623215_Characterization_of_Permafrost_Thermal_State_in_the_Southern_Yukon). *Proceedings of GEOQuebec 2015 Geotechnical Conference and 7th Canadian Permafrost Conference, Quebec City, Canada.*
3.  **Bevington AR** and AG Lewkowicz. 2015. [Assessment of a landcover driven TTOP-model for mountain and lowland permafrost using field data, southern Yukon and northern British Columbia, Canada](https://www.researchgate.net/publication/282649555_Assessment_of_a_land_cover_driven_TTOP_model_for_mountain_and_lowland_permafrost_using_field_data_southern_Yukon_and_northern_British_Columbia_Canada). *Proceedings of GEOQuebec 2015 Geotechnical Conference and 7th Canadian Permafrost Conference, Quebec City, Canada.*

# Presentations

1.  **Bevington AR**. 2019. Reproducible workflows in satellite remote sensing. BC Government Data Science Community of Practice Demo Day, Victoria, BC.

2.  **Bevington AR**. 2019. The magic of remote sensing. Northern Silviculture Committee Winter Conference, Prince George, BC.

3.  **Bevington AR**. 2018. When I fly, I always take the window seat. Oral Presentation, British Columbia Government "Research Talks". url: <https://youtu.be/WBWnnkhrCIA>.

4.  **Bevington AR**. 2018. Using satellite remote sensing for the quantification of surface water storage changes caused by the oil and gas sector in Northeastern British Columbia. Oral Presentation, British Columbia Government Hydraulic Fracturing Independent Review Panel.

5.  **Bevington AR**. 2017. The democratization of satellite remote sensing: Implications for science in British Columbia. Oral Presentation, NRESi Colloquium, University of Northern British Columbia, Prince George, British Columbia. url: <http://tinyurl.com/y3az54ct>.

6.  **Bevington AR**. 2017. The democratization of satellite remote sensing: Implications for the people of British Columbia. Oral Presentation, Science Week, Prince George Public Library, British Columbia.

7.  **Bevington AR**. 2017. A tour of the mountain cryosphere of British Columbia. Oral Presentation, Remote Sensing Research Seminar, University of Oslo, Norway.

8.  **Bevington AR** and B Menounos. 2017. Glacier area change in British Columbia over 31 years of satellite imagery using Google Earth Engine. Poster Presentation, European Space Agency 7th Advanced Land Remote Sensing Workshop, Gödöllö, Hungary.

9.  **Bevington AR** and B Menounos. 2017. Glacier area change in British Columbia over 31 years of satellite imagery. Oral Presentation, Canadian Geophysical Union, Vancouver, Canada.

10. **Bevington AR** and M Geertsema. 2016. Landslide response to the October 27, 2012 earthquake (Mw 7.7), Gwaii Haanas National Park Reserve and Haida Heritage Site, Haida Gwaii, BC. Oral Presentation. Whitehorse 2016 GAC-MAC Annual Meeting, Whitehorse, Canada.

11. **Bevington AR** and M Geertsema. 2016. Using remote sensing product to detect geohazards in the mountainous regions of northern British Columbia. Oral Presentation. Whitehorse 2016 GAC-MAC Annual Meeting, Whitehorse, Canada

12. **Bevington AR**. 2016. Professional development workshop: Remote sensing for natural resource practitioners. Oral Presentation, British Columbia Institute of Agrologists (BCIA) Annual General Meeting 2016, Prince George, Canada.

13. **Bevington AR**. 2016. Satellite remote sensing for the natural sciences. Webinar Presentation, Provincial Hydro/Geo Technical Working Group, Prince George, British Columbia.

14. **Bevington AR**, M van Der Kooij, M Geertsema, C Huggel. 2015. Detection and analysis of landslides following the April 25, 2015 Mw 7.8 Gorkha earthquake, Nepal using Radarsat-2 SAR data. Oral Presentation, Canadian Space Agency ASAR Workshop, Montreal, Quebec.
