---
title: "Curriculum Vitae"
pagetitle: "Alexandre R. Bevington"
output:
  html_document:
    toc: true
    number_sections: true
    toc_float: 
      collapsed: false
      smooth_scroll: true
---

<link rel="stylesheet" href="../styles.css" type="text/css"> <link rel="stylesheet" href="../academicicons/css/academicons.min.css"/>

Last updated `r lubridate::today()`

# Employment

-   **Research Hydrologist**, 2019-Present\
    Ministry of Forests, Lands, Natural Resource Operations and Rural Development\
    Prince George, British Columbia

-   **Research Earth Scientist**, 2015-2019\
    Ministry of Forests, Lands, Natural Resource Operations and Rural Development\
    Prince George, British Columbia

<!-- -   **College Instructor**, 2013-2014\ -->
<!--     Yukon College\ -->
<!--     Whitehorse, Yukon -->

<!-- -   **Graduate Field Researcher in Permafrost Science**, 2010-2014\ -->
<!--     University of Ottawa / Geological Survey of Canada\ -->
<!--     Ottawa, Ontario and Whitehorse, Yukon -->

<!-- -   **Teaching Assistant**, 2012-2013\ -->
<!--     University of Ottawa\ -->
<!--     Ottawa, Ontario -->

<!-- -   **Editorial Assistant**, 2012-2012\ -->
<!--     Canadian International Polar Year, Aboriginal Affairs and Northern Development Canada\ -->
<!--     Ottawa, Ontario -->

# Education

-   **PhD in Natural Resources and Environmental Studies**, Ongoing\
    University of Northern British Columbia (Prince George, British Columbia)\
    "Accelerated change in the mountain cryosphere of British Columbia"\
    Supervisors: Dr. B. Menounos and Dr. M Geertsema

-   **MSc in Physical Geography**, 2015\
    University of Ottawa (Ottawa, Ontario)\
    "Towards a TTOP-model of permafrost distribution for Yukon and British Columbia"\
    Supervisor: Dr. A. Lewkowicz

<!-- -   **BSc with Honors in Physical Geography**, 2011\ -->
<!--     University of Ottawa (Ottawa, Canada)\ -->
<!--     "Characteristics of the last five surges of Lowell Glacier, Yukon, Canada, since 1948"\ -->
<!--     Supervisor: Dr. L. Copland -->

# Publications

## Peer-reviewed publications

1.  [Classification of clustered snow off dates over British Columbia, Canada, from mean sea level pressure](https://doi.org/10.1080/07055900.2020.1845116)\
    Gleason, HG, **AR Bevington** and VN Foord. 2020.\
    Atmosphere-Ocean, 58, 333--350.

2.  [Regional moose (Alces alces) responses to forestry cutblocks are driven by landscape-scale patterns of vegetation composition and regrowth](https://doi.org/10.1016/j.foreco.2020.118763)\
    Mumma, MA, MP Gillingham, S Marshall, C Procter, **AR Bevington** and M Scheideman. 2020.\
    Forest Ecology and Management, 481, 1--11.

3.  [Near real-time wildfire progression monitoring with Sentinel-1 SAR time series and deep learning](https://doi.org/10.1038/s41598-019-56967-x)\
    Ban, Y, P Zhang, A Nascetti, **AR Bevington** and MA Wulder. 2020.\
    Scientific Reports, 10, 1322.

4.  [Landslide response to the 27 October 2012 earthquake (MW 7.8), southern Haida Gwaii, British Columbia, Canada](https://doi.org/10.1007/s10346-019-01292-7)\
    Barth, S, M Geertsema, **AR Bevington**, AL Bird, JJ Clague, T Millard, PT Bobrowsky, A Hasler and H Liu. 2020.\
    Landslides, 17, 517--526.

5.  [Semi-automated detection of landslide timing using harmonic modelling of satellite imagery, Buckinghorse River, Canada](https://doi.org/10.1016/j.jag.2019.101943)\
    Deijns, AAJ, **AR Bevington**, F van Zadelhoff, SM de Jong, M Geertsema and S McDougall. 2020.\
    International Journal of Applied Earth Observation and Geoinformation, 84, 101943.

6.  [Rapid worldwide growth of glacial lakes since 1990](https://doi.org/10.1038/s41558-020-0855-4)\
    Shugar, DH, A Burr, UK Haritashya, JS Kargel, CS Watson, MC Kennedy, **AR Bevington**, RA Betts, S Harrison and K Strattman. 2020.\
    Nature Climate Change, 10, 939--945.

7.  [A cautionary note for rock avalanche field investigation -- recent sequential and overlapping landslides in British Columbia](https://doi.org/10.1139/cgj-2019-0751)\
    Geertsema M and AR Bevington. 2019.\
    Canadian Geotechnical Journal.

8.  [Regional influence of ocean--atmosphere teleconnections on the timing and duration of MODIS-derived snow cover in British Columbia, Canada](https://doi.org/10.5194/tc-13-2693-2019)\
    **Bevington AR**, H Gleason, V Foord, H Griesbauer and WC Floyd. 2019.\
    The Cryosphere, 13, 2693--2712.

9.  [Evolution of the 2014 Vulcan Creek landslide-dammed lake, Yukon, Canada, using field and remote survey techniques](https://doi.org/10.1007/s10346-019-01199-3).\
    Brideau MA, DH Shugar, **AR Bevington**, M Willis and C Wong. 2019.\
    Landslides, 16, 1823--1840.

10. [A review of free optical satellite imagery for watershed scale landscape analysis](https://doi.org/10.22230/jwsm.2018v2n2a18)\
    **Bevington AR**, H Gleason, X Giroux-Bougard and J de Jong. 2018.\
    Confluence: Journal of Watershed Science, 2, 1--22.

11. [The Permafrost Young Researchers Network (PYRN) is getting older: The past, present, and future of our evolving community](https://doi.org/10.1017/S0032247418000645)\
    Tanski G, H Bergstedt, **AR Bevington**, et al. 2019.\
    Polar Record. 1-4.

12. [Resource selection of free-ranging horses influenced by fire in northern Canada](https://doi.org/10.26077/j5px-af63)\
    Leverkus S, SD Fuhlendorf, M Geertsema, BD Allred, M Gregory, **AR Bevington**, DM Engle and JD Scasta. 2018.\
    Human--Wildlife Interactions 12, 85--101.

13. [Geomorphic and tectonic controls of geohazards induced by Nepal's 2015Gorkha earthquake](https://doi.org/10.1126/science.aac8353)\
    Kargel JS, GJ Leonard ,DH Shugar, UK Haritashya, **AR Bevington**, et al. 2015.\
    Science, 351, 6269.

14. [Determination of warm, sensitive permafrost areas in near‐vertical rockwalls and evaluation of distributed models by electrical resistivity tomography](https://doi.org/10.1002/2014JF003351)\
    Magnin F, M Krautblatter, P Deline, L Ravanel, E Malet and **AR Bevington**. 2015.\
    Journal of Geophysical Research Earth Surface, 120, 745--762.

15. [Characteristics of the last five surges of Lowell Glacier, Yukon, Canada, since 1948](https://doi.org/10.3189/2014JoG13J134)\
    **Bevington AR** and L Copland. 2014.\
    Journal of Glaciology, 60, 219.

## Government publications

1.  [Snow cover timing from satellite imagery: Opportunities for near-real-time mapping and seasonal forecasting](http://a100.gov.bc.ca/pub/eirs/viewDocumentDetail.do?fromStatic=true&repository=BDP&documentId=13100)\
    **Bevington AR**, HE Gleason and VN Foord. 2020.\
    BC Technical Report 129. Government of British Columbia. Victoria, BC.Book Chapters

## Book chapters

1.  [Glacier Environments](https://doi.org/10.1007/978-3-319-12127-7_143-1)\
    Menounos B, **AR Bevington** and Geertsema, M. 2017.\
    In: Encyclopedia of Engineering Geology. P.T. Bobrowsky and B. Marker (eds.).\
2.  [The Diverse Landscapes of Haida Gwaii](https://doi.org/10.1007/978-3-319-44595-3_21)\
    **Bevington AR**, JJ Clague, T Millard, IJ Walker and M Geertsema. 2017.\
    In: Landscapes and Landforms of Western Canada. O. Slaymaker (ed.).
3.  [Mountain Environments](https://doi.org/10.1007/978-3-319-12127-7_209-1)\
    **Bevington AR**, MA Brideau and M Geertsema. 2016.\
    In: Encyclopedia of Engineering Geology. P.T. Bobrowsky and B. Marker (eds.).

## Refereed conference papers

1.  [Engineering geology,electrical resistivity tomography and displacement monitoring of the DawsonCity Landslide, Yukon](https://www.researchgate.net/publication/281939062_Engineering_Geology_Electrical_Resistivity_Tomography_and_Displacement_Monitoring_of_the_Dawson_City_Landslide_Yukon)\
    Brideau MA, **AR Bevington**, AG Lewkowicz and D Stead. 2015.\
    Proceedings of GEOQuebec 2015 Geotechnical Conference and 7th Canadian Permafrost Conference, Quebec City, Canada.
2.  [Characterization ofpermafrost thermal state in the southern Yukon](https://www.researchgate.net/publication/312623215_Characterization_of_Permafrost_Thermal_State_in_the_Southern_Yukon)\
    Smith SL, AG Lewkowicz, M Ednie, M Duguay and **AR Bevington**. 2015.\
    Proceedings of GEOQuebec 2015 Geotechnical Conference and 7th Canadian Permafrost Conference, Quebec City, Canada.
3.  [Assessment of a landcover driven TTOP-model for mountain and lowland permafrost using field data, southern Yukon and northern British Columbia, Canada](https://www.researchgate.net/publication/282649555_Assessment_of_a_land_cover_driven_TTOP_model_for_mountain_and_lowland_permafrost_using_field_data_southern_Yukon_and_northern_British_Columbia_Canada)\
    **Bevington AR** and AG Lewkowicz. 2015.\
    Proceedings of GEOQuebec 2015 Geotechnical Conference and 7th Canadian Permafrost Conference, Quebec City, Canada.

## Presentations

1.  **Bevington AR**. 2019. Reproducible workflows in satellite remote sensing. BC Government Data Science Community of Practice Demo Day, Victoria, BC.

2.  **Bevington AR**. 2019. The magic of remote sensing. Northern Silviculture Committee Winter Conference, Prince George, BC.

3.  **Bevington AR**. 2018. When I fly, I always take the window seat. Oral Presentation, British Columbia Government "Research Talks". url: <https://youtu.be/WBWnnkhrCIA>.

4.  **Bevington AR**. 2018. Using satellite remote sensing for the quantification of surface water storage changes caused by the oil and gas sector in Northeastern British Columbia. Oral Presentation, British Columbia Government Hydraulic Fracturing Independent Review Panel.

5.  **Bevington AR**. 2017. The democratization of satellite remote sensing: Implications for science in British Columbia. Oral Presentation, NRESi Colloquium, University of Northern British Columbia, Prince George, British Columbia. url: <http://tinyurl.com/y3az54ct>.

6.  **Bevington AR**. 2017. The democratization of satellite remote sensing: Implications for the people of British Columbia. Oral Presentation, Science Week, Prince George Public Library, British Columbia.

7.  **Bevington AR**. 2017. A tour of the mountain cryosphere of British Columbia. Oral Presentation, Remote Sensing Research Seminar, University of Oslo, Norway.

8.  **Bevington AR** and B Menounos. 2017. Glacier area change in British Columbia over 31 years of satellite imagery using Google Earth Engine. Poster Presentation, European Space Agency 7th Advanced Land Remote Sensing Workshop, Gödöllö, Hungary.

9.  **Bevington AR** and B Menounos. 2017. Glacier area change in British Columbia over 31 years of satellite imagery. Oral Presentation, Canadian Geophysical Union, Vancouver, Canada.

10. **Bevington AR** and M Geertsema. 2016. Landslide response to the October 27, 2012 earthquake (Mw 7.7), Gwaii Haanas National Park Reserve and Haida Heritage Site, Haida Gwaii, BC. Oral Presentation. Whitehorse 2016 GAC-MAC Annual Meeting, Whitehorse, Canada.

11. **Bevington AR** and M Geertsema. 2016. Using remote sensing product to detect geohazards in the mountainous regions of northern British Columbia. Oral Presentation. Whitehorse 2016 GAC-MAC Annual Meeting, Whitehorse, Canada

12. **Bevington AR**. 2016. Professional development workshop: Remote sensing for natural resource practitioners. Oral Presentation, British Columbia Institute of Agrologists (BCIA) Annual General Meeting 2016, Prince George, Canada.

13. **Bevington AR**. 2016. Satellite remote sensing for the natural sciences. Webinar Presentation, Provincial Hydro/Geo Technical Working Group, Prince George, British Columbia.

14. **Bevington AR**, M van Der Kooij, M Geertsema, C Huggel. 2015. Detection and analysis of landslides following the April 25, 2015 Mw 7.8 Gorkha earthquake, Nepal using Radarsat-2 SAR data. Oral Presentation, Canadian Space Agency ASAR Workshop, Montreal, Quebec.

<!-- # Awards -->

<!-- 1.  British Columbia Institute of Agrology, New Growth Award, 2020 -->

<!-- 2.  NSERC Canada Graduate Scholarship -- Doctoral (CGS-D), 2018-2020 -->

<!-- 3.  University of Northern British Columbia Graduate Travel Award, 2017 -->

<!-- 4.  University of Northern British Columbia Doctoral Tuition Fee Waiver, 2016-2020 -->

<!-- 5.  GLACIO-EX: Norwegian Cryospheric Exchange Scholarship, University of Oslo, 2014 -->

<!-- 6.  National Geographic Young Explorer Grant, 2013 -->

<!-- 7.  W. Garfield Weston Award for Northern Research (Master's) / Association of Canadian Universities for Northern Studies, 2013 -->

<!-- 8.  Northern Scientific Training Program from Aboriginal Affairs and Northern Development Canada, 2011-2013 -->

<!-- 9.  Research Fellowship, Northern Research Endowment Fund, Yukon Research Centre, Yukon College, 2013 -->

<!-- 10. High North Fellowship Program, Norwegian Government, 2013 -->

<!-- 11. Graduate Student Admission Scholarship, M.Sc. in Physical Geography, 2012-2014 -->

<!-- 12. NSERC CREATE Training Program Undergraduate Poster Award, 2012 -->

<!-- 13. NSERC USRA National Science and Engineering Research Council Undergraduate Student Research Award, 2011 -->

<!-- 14. CRYO-EX: Norwegian Cryospheric Exchange Scholarship, University of Oslo, 2010 -->

<!-- # Volunteering -->

<!-- 1.  **President**, [Prince George Backcountry Recreation Society](www.pgbrs.org), 2020-Present -->

<!-- 2.  **Conference Organizer**, Canadian Cartographic Association, 2019 -->

<!-- 3.  **Young National Correspondent**,GTN-P Canada, 2015-18 -->

<!-- 4.  **Mountain permafrost workshop coordinator**, Carleton University, 2014 -->

<!-- 5.  **Vice-President**, Permafrost Young Researcher Network, 2014-16 -->

<!-- 6.  **Volunteer Reviewer**, 4th European Conference on Permafrost (EUCOP4), 2014 -->

<!-- 7.  **Ski Patroller**, Canadian Ski Patrol, Yukon, 2013-14 -->

<!-- 8.  **Board Member**, Association of Polar Early Career Scientists (APECS) Canada, 2013-15 -->

<!-- 9.  **GIS Analyst**, Mining Watch Canada, 2013 -->

<!-- 10. **GIS Analyst**, GIS Corps, 2012-13 -->

<!-- 11. **Vice President Social**, Geography Graduate Student Association, University of Ottawa, 2012-13 -->

<!-- 12. **Lead Organizer**, University of Ottawa GIS Day 2012, 2012 -->

<!-- 13. **Youth Outreach**, NSERC Let's Talk Science, 2012-13 -->

<!-- 14. **Scientific Abstract Review Board Member**, ACUNS Student Conference, 2012 -->

<!-- 15. **Member of the Executive Council**, Association of Polar Early Career Scientists (APECS), 2011-12 -->

<!-- 16. **Student Senator**, Faculty of Science, University of Ottawa, 2009-10 -->

<!-- 17. **President**, Undergraduate Geography Student Association, University of Ottawa, 2007-09 -->
